### ISSUE TITLE
Upgrade lava-dnf to newest Lava version for release

### ISSUE THREAD

**Issue by mathisrichter** [lava-nc/lava-dnf#53]
### User story

As a user, I want to use lava-dnf with the newest version of lava and lava-loihi to have access to new features and performance optimizations.

### Conditions of satisfaction
- All tests are passing on lava-dnf when using the newest to-be-released version of lava and lava-loihi.

### Tasks
- [x] Check out newest versions of Lava, Lava-Loihi, and lava-dnf (MR)
- [x] Run all tests locally (1h, MR)
- [x] Fix hanging tutorial tests (1h, MR)
~~- [ ] Fix any incompatibilities (2h, MR)~~
~~- [ ] Code review (1h, MR)~~
~~- [ ] Merge code (MR)~~
