### ISSUE TITLE
Merge Motion Tracking into main of lava-dnf

### ISSUE THREAD

**Issue by PhilippPlank** [lava-nc/lava-dnf#70]
- [x] Make it terminate gracefully
- [x] Use connect function again
- [x] Bug fixes
- [ ] Check if Loihi is available, if not run in simulation otherwise on Loihi (follow lava-dl example) (optional)
- [x] Save the executable and run demo from stored executable (users can choose to recompile in the code)
- [x] Unit test in lava-loihi tests/lava/lib/dnf
- [ ] Merge PR in lava-dnf
- [ ] Merge PR in lava-loihi (unit test)
